добавлены изображения
htmlacademy-htmlcss/2223581-sedona-37 pull request #4
Opened 2023-06-15 10:49 UTC by MariaGuzenko

2023-06-16 16:43 UTC, Kartaviy-arteom requested changes
1. placeholer по всему документу. нужно placeholder
2. у label в  for  указывается id элемента

2023-06-16 16:43 UTC, Kartaviy-arteom commented on index.html
> +            <img class="infrastructure-icon" src="images/home.png" width="75" height="72" alt="Домик">
декоративные картинки нужно убрать из разметки, остаются только контентные

2023-06-16 16:43 UTC, Kartaviy-arteom commented on images/search.png
в svg

2023-06-16 16:43 UTC, Kartaviy-arteom commented on images/present.png
в svg

2023-06-16 16:43 UTC, Kartaviy-arteom commented on images/home.png
svg

2023-06-16 16:43 UTC, Kartaviy-arteom commented on images/favorite.png
svg и без цифр, только сердечко

2023-06-16 16:43 UTC, Kartaviy-arteom commented on images/Logo-footer.png
svg

2023-06-16 16:43 UTC, Kartaviy-arteom commented on catalog.html
> + <img class="Youtube" src="images/youtube.svg" width="20" height="20" alt="Youtube">
тоже декоративные

2023-06-16 16:43 UTC, Kartaviy-arteom commented on images/gordeous.svg
лучше экспортировать одной картинкой с другим текстом в этом блоке

2023-06-19 17:20 UTC, Kartaviy-arteom requested changes

2023-06-19 17:20 UTC, Kartaviy-arteom commented on index.html
> +        <img class="footer-social-logo" href="https://htmlacademy.ru/" src="images/Logo-footer.png "
обернуть в ссылку

2023-06-19 17:20 UTC, Kartaviy-arteom commented on index.html
> +        <p class="phone">+7 (812) 812-12-12 </p>
ссылка

2023-06-19 17:20 UTC, Kartaviy-arteom commented on index.html
> +          <input class="btn" type="submit" value="Найти">
кнопка button type submit

2023-06-19 17:20 UTC, Kartaviy-arteom commented on index.html
> +        <br>
br

2023-06-20 06:21 UTC, MariaGuzenko commented on index.html
> +            <img class="infrastructure-icon" src="images/home.png" width="75" height="72" alt="Домик">
убрала

2023-06-20 06:22 UTC, MariaGuzenko commented on images/search.png
убрала декоративные картинки, будут в стилях

2023-06-20 06:23 UTC, MariaGuzenko commented on images/present.png
убрала декоративные картинки, будут в стилях

2023-06-20 06:23 UTC, MariaGuzenko commented on images/home.png
убрала декоративные картинки, будут в стилях

2023-06-20 06:23 UTC, MariaGuzenko commented on images/favorite.png
убрала декоративные картинки, будут в стилях

2023-06-20 06:23 UTC, MariaGuzenko commented on images/Logo-footer.png
скорректировала в svg

2023-06-20 06:23 UTC, MariaGuzenko commented on catalog.html
> + <img class="Youtube" src="images/youtube.svg" width="20" height="20" alt="Youtube">
убрала декоративные

2023-06-20 06:23 UTC, MariaGuzenko commented on images/gordeous.svg
экспорт в svg и добавила в разметку

2023-06-20 13:12 UTC, merged

2023-06-23 16:29 UTC, Kartaviy-arteom commented on images/favorite.png
нужно импортировать только иконку без счетчика

2023-06-23 16:29 UTC, Kartaviy-arteom commented on images/gordeous.svg
это все вместе одна картинка because.svg

2023-06-23 16:29 UTC, Kartaviy-arteom commented on images/food.png
это в svg

2023-06-23 16:29 UTC, Kartaviy-arteom commented on images/home.png
это в svg

2023-06-23 16:29 UTC, Kartaviy-arteom commented on images/present.png
это в svg

2023-06-23 16:29 UTC, Kartaviy-arteom commented on images/search.png
это в svg

2023-06-23 16:29 UTC, Kartaviy-arteom commented on index.html
> +            <ul class="advantages-advices">
а почему это тут?

2023-06-26 13:45 UTC, MariaGuzenko commented on index.html
> +        <img class="footer-social-logo" href="https://htmlacademy.ru/" src="images/Logo-footer.png "
<a class="footer-social-link link" href="https://www.youtube.com/user/htmlacademyru"></a>   обновила

2023-06-26 13:46 UTC, MariaGuzenko commented on index.html
> +        <p class="phone">+7 (812) 812-12-12 </p>
<a class="footer-social-link link" href="https://www.youtube.com/user/htmlacademyru"></a>   обновила

2023-06-26 13:48 UTC, MariaGuzenko commented on index.html
> +          <input class="btn" type="submit" value="Найти">
исправлено

2023-06-26 13:48 UTC, MariaGuzenko commented on index.html
> +        <br>
убрала

2023-06-26 14:05 UTC, MariaGuzenko commented on images/favorite.png
заменила

2023-06-26 14:10 UTC, MariaGuzenko commented on images/gordeous.svg
заменила на images/welcome.svg

2023-06-26 14:12 UTC, MariaGuzenko commented on images/food.png
done

2023-06-26 14:13 UTC, MariaGuzenko commented on images/home.png
done

2023-06-26 14:13 UTC, MariaGuzenko commented on images/present.png
done

2023-06-26 14:14 UTC, MariaGuzenko commented on images/search.png
done

2023-06-26 14:16 UTC, MariaGuzenko commented on index.html
> +            <ul class="advantages-advices">
fixed