Базовая стилизация
htmlacademy-htmlcss/2223581-sedona-37 pull request #5
Opened 2023-06-26 20:28 UTC by MariaGuzenko

2023-06-30 16:21 UTC, Kartaviy-arteom requested changes
1.<input class="btn" type="submit" value="Найти"> исправить на button и шрифты в инпутах
2. убрать декоративные картинки из разметки
3. валидность разметки

2023-06-30 16:21 UTC, Kartaviy-arteom commented on images/Line 7.png
это тебе не нужно

2023-06-30 16:21 UTC, Kartaviy-arteom commented on images/Rectangle 125.svg
это думаю тоже

2023-06-30 16:21 UTC, Kartaviy-arteom commented on images/catalog-back.png
выгрузи это изображение в jpg

2023-06-30 16:21 UTC, Kartaviy-arteom commented on images/vectordown.svg
наименование файлов в соответствии с критериями

2023-06-30 16:21 UTC, Kartaviy-arteom commented on styles/styles.css
> +    align-items: center;
вот эти стили можно вынести просто в button, а здесь оставить цвет

2023-06-30 16:21 UTC, Kartaviy-arteom commented on styles/styles.css
> +    line-height: 36px;
у этой кнопки в хедере другой font-size

2023-06-30 16:21 UTC, Kartaviy-arteom commented on styles/styles.css
> +    padding: 2px 1px 1px 1px;
для чего такой странный паддинг?

2023-06-30 16:21 UTC, Kartaviy-arteom commented on styles/styles.css
> +  .advantages-description {
цвет текста и в аналогичный блоках

2023-06-30 16:21 UTC, Kartaviy-arteom commented on styles/styles.css
> +    padding: 8px 50px;
тебе не нужны такие падинги горизонтальные

2023-07-04 11:55 UTC, merged

2023-07-10 12:09 UTC, MariaGuzenko commented on images/Line 7.png
удалила

2023-07-10 12:09 UTC, MariaGuzenko commented on images/Rectangle 125.svg
удалила

2023-07-10 12:12 UTC, MariaGuzenko commented on images/catalog-back.png
готово

2023-07-10 12:13 UTC, MariaGuzenko commented on images/vectordown.svg
исправила на divider

2023-07-10 12:16 UTC, MariaGuzenko commented on styles/styles.css
> +    align-items: center;
готово

2023-07-10 12:17 UTC, MariaGuzenko commented on styles/styles.css
> +    line-height: 36px;
исправила

2023-07-10 12:18 UTC, MariaGuzenko commented on styles/styles.css
> +    padding: 2px 1px 1px 1px;
убрала

2023-07-10 12:27 UTC, MariaGuzenko commented on styles/styles.css
> +  .advantages-description {
исправила цвет

2023-07-10 12:29 UTC, MariaGuzenko commented on styles/styles.css
> +    padding: 8px 50px;
убрала