Сетки страниц на флексах
htmlacademy-htmlcss/2223581-sedona-37 pull request #6
Opened 2023-07-10 15:20 UTC by MariaGuzenko

2023-07-10 16:37 UTC, Kartaviy-arteom requested changes

2023-07-10 16:37 UTC, Kartaviy-arteom commented on index.html
> +          </ul>
сломалась валидность

2023-07-10 16:37 UTC, Kartaviy-arteom commented on index.html
> +              <h4 class="advices-title advices-title-housing headings">Жилье</h4>
уровни заголовков

2023-07-10 16:37 UTC, Kartaviy-arteom commented on index.html
> +                  <button class="calendar" type="button"></button>
тут нет кнопки, это декоративная картинка. Ниже аналогично

2023-07-10 16:37 UTC, Kartaviy-arteom commented on index.html
> +        <div class="modal-container modal-container-close">
модальное окно перед закрывающим body должно быть

2023-07-10 16:37 UTC, Kartaviy-arteom commented on index.html
> +              </p>
ты можень обернуть это все в параграф, но не разбивать так. Если тебе нужен элемент для группировки без смысловой нагрузки используй div

2023-07-10 16:37 UTC, Kartaviy-arteom commented on index.html
> +          <img class="footer-social-logo" src="images/logo-footer.svg " alt="Логотип.">
лучше давать более осмысленные описание картинкам

2023-07-10 16:37 UTC, Kartaviy-arteom commented on index.html
> +                <svg class="navigation-icon" aria-hidden="true" focusable="false" width="19" height="17" viewBox="0 0 19 17" xmlns="http://www.w3.org/2000/svg">
https://up.htmlacademy.ru/htmlcss/37/criteries#IMG-01

2023-07-13 15:02 UTC, MariaGuzenko commented on index.html
> +          </ul>
исправила

2023-07-13 15:02 UTC, MariaGuzenko commented on index.html
> +              <h4 class="advices-title advices-title-housing headings">Жилье</h4>
исправила

2023-07-13 15:03 UTC, MariaGuzenko commented on index.html
> +                  <button class="calendar" type="button"></button>
готово

2023-07-13 15:03 UTC, MariaGuzenko commented on index.html
> +              </p>
готово

2023-07-13 15:03 UTC, MariaGuzenko commented on index.html
> +        <div class="modal-container modal-container-close">
готово

2023-07-19 12:13 UTC, merged